---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-github-actions-dependencies:
        # GitHub Actions: Only group minor and patch updates
        update-types: [minor, patch]
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      patch-pip-dependencies:
        # pip: Only group patch updates
        update-types: [patch]
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      patch-terraform-dependencies:
        # terraform: Only group patch updates
        update-types: [patch]
